### ISSUE TITLE
What reference was used for real-world currency conversion.

### ISSUE THREAD

**Issue by JonasunderscoreJones** [the-real-finnventor/galleon-convertion-website#1]
First of all Cool Project, I've been looking for a converter to real life currency and this is just perfect.

I just have a question about what you used as a reference for the conversion rate from Galleons to USD as I couldn't find any conclusive information on this topic. My guess would be that you probably looked at prices from various items in the franchise and in the real world to approximate the rate you are using. Is this what you did or is there an actual reference somewhere that I missed?

Cheers!

**Comment by the-real-finnventor** [comment]
It was a while ago that I made this project but I believe I got the conversions from [this website](https://harry-potter-compendium.fandom.com/wiki/Wizarding_currency), if you scroll down there is [this chart](https://github.com/user-attachments/assets/f75e44c0-6d24-4fe8-b800-333f33f7cea2).

**Comment by JonasunderscoreJones** [comment]
That's perfect. thank You very much!
